# Create a new offer
POST http://localhost:3333/api/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Куплю-продам все товары 0308",
  "description": "Новый детективный роман от короля ужасов.",
  "image": "./item05.jpg",
  "type": "Buy",
  "price": 1700,
  "categories": "64a572513c982381512b3d78",
  "userId": "64b6a818cf3de47853a3d00e"
}

###

# Delete the offer by id
DELETE http://localhost:3333/api/offers/64b4d5edc18178c33c60e82f HTTP/1.1

###

# Get offers by category id
GET http://localhost:3333/api/offers/64a572513c982381512b3d78/offers HTTP/1.1

###

# Get offer by id
GET http://localhost:3333/api/offers/64ca3a926524f37866f9fcd1 HTTP/1.1

###

# Get new posts
GET http://localhost:3333/api/offers/bundles/new HTTP/1.1

###

# Get all posts
GET http://localhost:3333/api/offers HTTP/1.1

###

PATCH http://localhost:3333/api/posts/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Новый заголовок"
}

###
